### ISSUE TITLE
problem during persistentvolume claim

### ISSUE THREAD

**Issue by matteofcorona** [digexp/DX.Kubernetes.IBM-Cloud#1]
Hi,
I am facing the problem as soon as I try to import the file PersistentVolumeClaim.yml.
The import works correctly but it seem stuck at pending state for ever.
I launched the command
[root@portalv90CE DX.Kubernetes.IBM-Cloud]# **kubectl describe pvc portal-profile**
Name:          portal-profile
Namespace:     default
StorageClass:  ibmc-file-retain-custom
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-class=ibmc-file-retain-custom
Capacity:
Access Modes:
Events:
  Type     Reason              Age                From                         Message
  Warning  ProvisioningFailed  2m (x242 over 1h)  persistentvolume-controller  storageclass.storage.k8s.io "ibmc-file-retain-custom" not found

I also tried to launch without the storage class:

[root@portalv90CE DX.Kubernetes.IBM-Cloud]# **kubectl describe pvc portal-profile**
Name:          portal-profile
Namespace:     default
StorageClass:
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-class=
Capacity:
Access Modes:
Events:
  Type    Reason         Age               From                         Message
  Normal  FailedBinding  2s (x3 over 25s)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

could you please provide instructions on how to proceed ?

**Comment by georgefridrich** [comment]
Hi Matt,
The PV is required for WebSphere Portal to be stateful, the Portal deployment yaml looks for the PV and will not deploy until it is bound.  If you don't require Portal to be stateful I can provide to you a deployment yaml  that will not require the pvc to exist.
For the main issue you are having with the PV, what is taking place is a NFS space is being created in IBM Cloud to store the Portal profile (wp_profile).  This NFS space is not free so you will need an account that allows for changes to billing.  What you can do is go to the dashboard on IBM Cloud, open the menu in the upper left corner and choose infrastructure.  Then select storage and then file storage in the left tree nav window.  You should be able to see the created volume and hopefully get a bit more information on why it is failing to deploy.  Please let me know what you find and we'll get this sorted and resolved for you asap.  Thanks.

**Comment by matteofcorona** [comment]
Hi, thank you for you quick response.
Since I am now using an account free (even if I am an IBMer), I think I am not able due to the fact of that.
If I search for the storage in my IBM cloud dashboard this is empty and if I want to create a new one the system tell me I have to upgrade my account.
Maybe I can ask you internally how I can proceed to upgrade my account (if this is the main cause of my problem now)

**Comment by georgefridrich** [comment]
Closing this issue Matteo since we have taken care of your issue internally.  Resolution is to have a paid bluemix account.  In order for Portal to be stateful we require an NFS space in the cloud and there is a small fee associated with having that space each month.  We can make this work on a free bx acct. however Portal will not be stateful.  Thanks.
